# Generated by Django 3.2.5 on 2021-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.PositiveIntegerField()),
                ('id_user', models.PositiveIntegerField()),
            ],
        ),
    ]
