# Generated by Django 3.2.4 on 2021-06-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_id_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ava', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('secondName', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='id_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.artist'),
        ),
    ]
