# Generated by Django 3.2.4 on 2021-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20210625_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(),
        ),
    ]
